apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: url-shortener-service
    version: v1
  name: url-shortener-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener-service
      version: v1
  template:
    metadata:
      labels:
        app: url-shortener-service
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      volumes:
        - name: secretvolume
          secret:
            secretName: datasource
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -Dspring.profiles.active=dev
          name: url-shortener-service
          image: demo/url-shortener-service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
          volumeMounts:
            - name: secretvolume
              mountPath: /stuff/secrets
              readOnly: true
          resources:
            requests:
              memory: "200Mi"
              cpu: "1000m" # 1 core
            limits:
              memory: "300Mi"
              cpu: "1500m"
          livenessProbe:
            exec:
              command:
                - curl
                - localhost:8080/health/live
            initialDelaySeconds: 30
            periodSeconds: 4
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - curl
                - localhost:8080/health/ready
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
          securityContext:
            privileged: false